# 🚀 Why Use NumPy?

Python lists are **flexible but slow** for numerical computing because they:

- Store elements as **pointers** instead of a continuous memory block  
- Lack **vectorized operations** (rely on loops instead)  
- Have significant overhead due to **dynamic typing**  

---

## 🌟 NumPy’s Superpowers

✅ Faster than Python lists (**C-optimized backend**)  
✅ Uses less memory (**efficient storage**)  
✅ Supports **vectorized operations** (no explicit loops)  
✅ Provides **built-in mathematical functions**  

---

## ⚡ NumPy vs. Python Lists – Performance Test

Let’s compare performance between Python lists and NumPy arrays.

```python
import numpy as np
import time

# Python list
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x + y for x, y in zip(list1, list2)]
end = time.time()
print("Python list addition time:", end - start)

# NumPy array
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1 + arr2  # Vectorized operation
end = time.time()
print("NumPy array addition time:", end - start)
````

🔑 **Key Takeaway:** NumPy is significantly **faster** because it performs operations in **C**, avoiding Python loops.

---

## 🏗️ Creating NumPy Arrays

```python
import numpy as np

# 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)
```

🔹 NumPy stores data in a **contiguous memory block**, making access faster than lists.
🔹 `shape` shows the **dimensions** of an array.

---

## 🧠 Memory Efficiency – NumPy vs. Lists

```python
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")
```

👉 NumPy arrays use **significantly less memory** compared to Python lists.

---

## ⚙️ Vectorization – No More Loops!

NumPy avoids explicit loops by applying operations to entire arrays at once using **SIMD** (Single Instruction, Multiple Data) and other low-level optimizations.
SIMD is a **CPU-level optimization** provided by modern processors.

### Example: Squaring Elements

```python
# Python list (loop-based)
list_squares = [x ** 2 for x in list1]

# NumPy (vectorized)
numpy_squares = arr1 ** 2
```

✅ NumPy is **cleaner and faster!**

---

## 📌 Summary

* NumPy is **faster** than Python lists (optimized in C).
* It consumes **less memory** due to efficient storage.
* It supports **vectorized operations**, eliminating slow loops.
* It is **essential** for Data Science & Machine Learning workflows.

---

## 📝 Exercises for Practice

1. Create a NumPy array with values from **10 to 100** and print its shape.
2. Compare the **time taken** to multiply two Python lists vs. two NumPy arrays.
3. Find the **memory size** of a NumPy array with **1 million elements**.

---

```

In [1]:
# Python Zip Explained
l1 = [1, 2, 4]
l2 = [6, 7, 8]
list(zip(l1,l2))

[(1, 6), (2, 7), (4, 8)]

In [2]:
# Using Python Lists
import numpy as np
import time

size = 1_000_00

l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x+y for x,y in zip(l1, l2)]
end = time.time()
print(add[0:10])

print(end - start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.0041027069091796875


In [3]:
# Using Numpy Arrays
import numpy as np
import time

size = 1_00_000

l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1 + l2
end = time.time()
print(add[0:10])

print(end - start)

[ 0  2  4  6  8 10 12 14 16 18]
0.0011279582977294922


In [4]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(2, 3)

In [9]:
import sys
list_data = list(range(1000))
numpy_data = np.array(list_data)
print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes
