# 🎯 Indexing and Slicing in NumPy

Indexing and slicing in NumPy works similarly to Python lists, but with **extra power** and **efficiency**.  

---

## 1️⃣ Indexing (Same as Python Lists)

```python
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr[0])   # 10 (first element)
print(arr[-1])  # 40 (last element)
````

---

## 2️⃣ Slicing (Extracting Parts of an Array)

```python
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])   # [20 30 40] → slice from index 1 to 3
print(arr[:3])    # [10 20 30] → first 3 elements
print(arr[::2])   # [10 30 50] → every 2nd element
```

---

## ⚠️ Important: Slicing Returns a **View, Not a Copy**

In **Python lists**, slicing creates a copy.
But in **NumPy arrays**, slicing creates a **view** that shares memory with the original array.

👉 Changes in the slice **affect the original** array!

```python
arr = np.array([10, 20, 30, 40, 50])
sliced = arr[1:4]
sliced[0] = 999

print(arr)  
# [10 999 30 40 50]
```

### Why?

* **Memory Efficiency** → Avoids unnecessary copies
* **Performance** → Faster access & manipulation on large datasets

💡 Use `.copy()` if you need an independent array.

```python
copy_arr = arr[1:4].copy()
```

---

## 3️⃣ Fancy Indexing

Fancy indexing lets you pick multiple elements **by index positions**.

```python
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]
print(arr[idx])  # [10 30 50]
```

---

## 4️⃣ Boolean Masking (Filtering Data)

You can use conditions to extract values that meet certain criteria.

```python
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25
print(mask)      # [False False  True  True  True]
print(arr[mask]) # [30 40 50]
```

✅ This is extremely powerful for **filtering large datasets** efficiently.

---

## 📌 Summary

* NumPy arrays are **faster and more memory-efficient** than lists.
* Use **indexing & slicing** for efficient data access.
* **Slicing returns a view** (shared memory). Use `.copy()` for independence.
* **Fancy indexing** selects multiple elements at once.
* **Boolean masking** filters data based on conditions.

---

## 📝 Exercises for Practice

1. Create a **3×3 array** filled with random numbers and print its shape.
2. Convert an array of floats `[1.1, 2.2, 3.3]` into integers.
3. Use **fancy indexing** to extract even numbers from `[1, 2, 3, 4, 5, 6]`.
4. Reshape a 1D array of size 9 into a **3×3 matrix**.
5. Use **boolean masking** to filter numbers greater than 50 in an array.

---

# Indexing and slicing

In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [3]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
flat = arr.flatten()

In [5]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
flat[0]

np.int64(1)

In [7]:
flat[3:6] # slice from index 3 to 5

array([4, 5, 6])

In [8]:
flat[:5] # same as flat[0:5], first 5 elements

array([1, 2, 3, 4, 5])

In [9]:
flat[3:] # same as flat[3:12]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
flat[::2] # every 2nd element

array([ 1,  3,  5,  7,  9, 11])

In [11]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
b = flat[3:7]

In [13]:
b

array([4, 5, 6, 7])

In [14]:
b[0] = 444

In [15]:
b

array([444,   5,   6,   7])

In [16]:
flat

array([  1,   2,   3, 444,   5,   6,   7,   8,   9,  10,  11,  12])

In [17]:
b = flat[3:7].copy() # This is not a slice because we are using copy method to get the copy.

In [18]:
b

array([444,   5,   6,   7])

In [19]:
b[0] = 445566

In [20]:
b

array([445566,      5,      6,      7])

In [21]:
flat

array([  1,   2,   3, 444,   5,   6,   7,   8,   9,  10,  11,  12])

# Fancy Indexing & Boolean Masking

## 1. Fancy Indexing (Select Multiple Elements)

In [22]:
arr1 = np.array([1, 54, 23, 53, 2, 3, 34, 5, 6])

In [23]:
arr1[[1, 4, 6]]  # Indices to select

array([54,  2, 34])

## 2. Boolean Masking (Filter Data)

In [24]:
arr2 = np.array([10, 20, 30, 40, 50])
mask = arr2 > 25  # Condition: values greater than 25
print(arr2[mask])  # [30 40 50]

[30 40 50]


In [25]:
arr1[arr1>23]

array([54, 53, 34])