# 🏋️ NumPy Practice Exercises

Time to apply what you’ve learned! Try these exercises on your own.  
(Hints are provided, but don’t peek until you need them 😉)

---

### 1️⃣ Create a 3×3 array filled with random numbers and print its shape.
```python
import numpy as np

arr = np.random.rand(3, 3)   # Hint: rand() generates random floats [0,1)
print(arr)
print("Shape:", arr.shape)
````

---

### 2️⃣ Convert an array of floats `[1.1, 2.2, 3.3]` into integers.

```python
arr = np.array([1.1, 2.2, 3.3])
arr_int = arr.astype(int)   # Hint: use .astype()
print(arr_int)
```

---

### 3️⃣ Use fancy indexing to extract even numbers from `[1, 2, 3, 4, 5, 6]`.

```python
arr = np.array([1, 2, 3, 4, 5, 6])
idx = [1, 3, 5]   # Hint: positions of even numbers
print(arr[idx])
```

💡 Extra challenge: Instead of hardcoding indices, build them dynamically with boolean masking.

```python
print(arr[arr % 2 == 0])
```

---

### 4️⃣ Reshape a 1D array of size 9 into a 3×3 matrix.

```python
arr = np.arange(1, 10)   # Creates [1,2,...,9]
reshaped = arr.reshape(3, 3)
print(reshaped)
```

---

### 5️⃣ Use boolean masking to filter numbers greater than 50 in an array.

```python
arr = np.array([10, 25, 55, 60, 5, 99])
mask = arr > 50
print(arr[mask])
```

---

✅ These exercises reinforce:

* Array creation
* Data type conversion
* Fancy indexing
* Reshaping
* Boolean masking

---

### 1. Create a 3×3 array filled with random numbers and print its shape.

In [1]:
import numpy as np

In [2]:
num = np.full((3,3), 10)

In [3]:
print("Shape:", num.shape)   # (4, 3) → 4 rows, 3 columns

Shape: (3, 3)


### 2. Convert an array of floats [1.1, 2.2, 3.3] into integers.

In [4]:
float_to_int = np.array([[ 1.0,  2.0,  3.0],[ 4.0,  5.0,  6.0],[ 7.0,  8.0,  9.0],[11.0, 12.0, 13.0],[14.0, 15.0, 16.0]], dtype = 'int64')

In [5]:
float_to_int

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16]])

### 3. Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

In [6]:
# Original array
arr = np.array([1, 2, 3, 4, 5, 6])

# Fancy indexing with a boolean mask for even numbers
even_numbers = arr[arr % 2 == 0]

print(even_numbers)

[2 4 6]


### 4. Reshape a 1D array of size 9 into a 3×3 matrix.

In [7]:
# 1D array of size 9
arr2 = np.arange(1, 10)

In [8]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# Reshape into 3x3
reshaped = arr2.reshape(3,3)

In [10]:
reshaped

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 5. Use boolean masking to filter numbers greater than 50 in an array.

In [11]:
# Example array
arr = np.array([10, 25, 50, 55, 60, 80, 45])

# Boolean mask for numbers > 50
mask = arr > 50

# Apply the mask
result = arr[mask]

print(result)

[55 60 80]
