# 🔄 Indexing and Axes in Multidimensional NumPy Arrays

NumPy allows you to efficiently work with **multidimensional arrays**, where **indexing** and **axis manipulation** are essential.  
This is crucial for **data science** and **machine learning**, where datasets often come in 2D (tables) or 3D (images, sequences).

---

## 1️⃣ Understanding Axes in NumPy

Each dimension in a NumPy array is called an **axis**, numbered from `0`.

- **1D array** → 1 axis (`axis=0`)  
- **2D array** → 2 axes (`axis=0` → rows, `axis=1` → columns)  
- **3D array** → 3 axes (`axis=0` → depth, `axis=1` → rows, `axis=2` → columns)  

### Example: Axes in a 2D Array
```python
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr)
````

Output:

```
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```

* **Axis 0 (rows)** → operations move **down the columns**
* **Axis 1 (columns)** → operations move **across the rows**

```python
print(np.sum(arr, axis=0))  # Sum down columns
print(np.sum(arr, axis=1))  # Sum across rows
```

Output:

```
[12 15 18]   # Column-wise sum
[ 6 15 24]   # Row-wise sum
```

---

## 2️⃣ Indexing in Multidimensional Arrays

You can access elements using **row and column indices**.

```python
# Accessing a single element
print(arr[1, 2])  # Row 1, Column 2 → 6
```

You can also use slicing:

```python
print(arr[0:2, 1:3])  # First 2 rows, last 2 columns
```

Output:

```
[[2 3]
 [5 6]]
```

---

## 3️⃣ Indexing in 3D Arrays

For **3D arrays**, the first index refers to the **depth (sheet)**.

```python
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

print(arr3D.shape)  # (2, 2, 3) → (depth, rows, columns)
```

Accessing elements:

```python
print(arr3D[0, 1, 2])   # First sheet, 2nd row, 3rd column → 6
print(arr3D[:, 0, :])   # First row from both sheets
```

Output:

```
[[1 2 3]
 [7 8 9]]
```

---

## 4️⃣ Practical Examples: Selecting Data Along Axes

### Example 1: Get all rows of the first column

```python
first_col = arr[:, 0]
print(first_col)
```

Output:

```
[1 4 7]
```

### Example 2: First row from each "sheet" in a 3D array

```python
first_rows = arr3D[:, 0, :]
print(first_rows)
```

Output:

```
[[1 2 3]
 [7 8 9]]
```

---

## 5️⃣ Changing Data Along an Axis

You can directly **modify elements along an axis**.

```python
arr[:, 1] = 0   # Replace all values in column 1 with 0
print(arr)
```

Output:

```
[[1 0 3]
 [4 0 6]
 [7 0 9]]
```

---

## 📌 Summary

* **Axis 0 = rows** (vertical), **Axis 1 = columns** (horizontal)
* Indexing: `arr[row, col]` (2D), `arr[depth, row, col]` (3D)
* **Slicing** extracts subarrays without copying data
* Axis operations allow efficient manipulation **without loops**

---

In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr[0]

array([1, 2, 3])

In [5]:
np.sum(arr, axis=0)   # Sum along rows (down each column)

array([12, 15, 18])

In [6]:
np.sum(arr, axis=1)  # Sum along columns (across each row) 

array([ 6, 15, 24])

In [7]:
arr[0][2]

np.int64(3)

In [9]:
arr[0:2, 1:3]  # Extracts first 2 rows and last 2 columns

array([[2, 3],
       [5, 6]])

In [17]:
arr3D = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
                  
[[7, 8, 9],
 [10, 11, 12]]
])

In [18]:
# Output of arr3D.shape is → (depth, rows, columns)
arr3D[:, 0, :]

array([[1, 2, 3],
       [7, 8, 9]])

In [19]:
arr3D[:, 0, :] = 0

In [20]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])