# Built in Mathematical functions in Numpy
Here are some common NumPy methods that are frequently used for statistical and mathematical operations:

1. **`np.mean()`** – Compute the **mean** (average) of an array.
   ```python
   np.mean(arr)
   ```

2. **`np.std()`** – Compute the **standard deviation** of an array.
   ```python
   np.std(arr)
   ```

3. **`np.var()`** – Compute the **variance** of an array.
   ```python
   np.var(arr)
   ```

4. **`np.min()`** – Compute the **minimum** value of an array.
   ```python
   np.min(arr)
   ```

5. **`np.max()`** – Compute the **maximum** value of an array.
   ```python
   np.max(arr)
   ```

6. **`np.sum()`** – Compute the **sum** of all elements in an array.
   ```python
   np.sum(arr)
   ```

7. **`np.prod()`** – Compute the **product** of all elements in an array.
   ```python
   np.prod(arr)
   ```

8. **`np.median()`** – Compute the **median** of an array.
   ```python
   np.median(arr)
   ```

9. **`np.percentile()`** – Compute the **percentile** of an array.
   ```python
   np.percentile(arr, 50)  # For the 50th percentile (median)
   ```

10. **`np.argmin()`** – Return the **index of the minimum** value in an array.
    ```python
    np.argmin(arr)
    ```

11. **`np.argmax()`** – Return the **index of the maximum** value in an array.
    ```python
    np.argmax(arr)
    ```

12. **`np.corrcoef()`** – Compute the **correlation coefficient** matrix of two arrays.
    ```python
    np.corrcoef(arr1, arr2)
    ```

13. **`np.unique()`** – Find the **unique elements** of an array.
    ```python
    np.unique(arr)
    ```

14. **`np.diff()`** – Compute the **n-th differences** of an array.
    ```python
    np.diff(arr)
    ```

15. **`np.cumsum()`** – Compute the **cumulative sum** of an array.
    ```python
    np.cumsum(arr)
    ```

16. **`np.linspace()`** – Create an array with **evenly spaced numbers** over a specified interval.
    ```python
    np.linspace(0, 10, 5)  # 5 numbers from 0 to 10
    ```

17. **`np.log()`** – Compute the **natural logarithm** of an array.
    ```python
    np.log(arr)
    ```

18. **`np.exp()`** – Compute the **exponential** of an array.
    ```python
    np.exp(arr)
    ```

These methods are used for performing mathematical and statistical operations with NumPy

# 🌟 NumPy Functions – The Party Analogy

Imagine your array `arr = [3, 5, 2, 33]` as a **group of party guests**, each carrying a different number of candies. Each NumPy function is like a **party activity** that tells you something about your guests’ candy behavior.

---

### 1️⃣ Mean (`np.mean(arr)`)  
**The average candies per guest.**  
- Imagine you collect all candies and divide equally among everyone.  
- `mean = (3 + 5 + 2 + 33) / 4 = 10.75`  
- Everyone would get roughly 10–11 candies.

---

### 2️⃣ Standard Deviation (`np.std(arr)`)  
**How wild the candy distribution is.**  
- If most guests have close to 10 candies, SD is low.  
- If one guest has 33 while others have 2–5, SD is high.  
- It measures **spread from the mean**.

---

### 3️⃣ Variance (`np.var(arr)`)  
- Just the **SD squared**.  
- Think of it as the "squared chaos" in candy distribution.  

---

### 4️⃣ Min & Max (`np.min(arr)` / `np.max(arr)`)  
- **Who has the least?** → `min = 2`  
- **Who has the most?** → `max = 33`  

---

### 5️⃣ Sum & Product (`np.sum(arr)` / `np.prod(arr)`)  
- **Sum:** Total candies in the party → `sum = 43`  
- **Product:** If every guest combined candies in a magic multiplication box → `prod = 3*5*2*33 = 990`  

---

### 6️⃣ Median (`np.median(arr)`)  
- Sort the candies `[2,3,5,33]` → the **middle candy count** = 4  
- If two middles, average them.  
- It’s the **middle guest’s candies**.

---

### 7️⃣ Percentile (`np.percentile(arr, 50)`)  
- The 50th percentile = median → half of guests have **≤ 4 candies**, half have **≥ 4**.  
- The 90th percentile would tell you **who’s in the top 10% candy holders**.

---

### 8️⃣ Argmin & Argmax (`np.argmin(arr)` / `np.argmax(arr)`)  
- **Who holds the fewest candies?** → index = 2  
- **Who holds the most candies?** → index = 3  

---

### 9️⃣ Correlation (`np.corrcoef(arr1, arr2)`)  
- Imagine a second party array `arr2 = [10, 20, 30, 40]`.  
- Correlation tells you **if candies in party 1 and party 2 “dance together”** (move in sync).

---

### 🔟 Unique (`np.unique(arr)`)  
- **How many different candy counts exist?** → `[2, 3, 5, 33]`  

---

### 1️⃣1️⃣ Difference (`np.diff(arr)`)  
- **Difference between each guest’s candies:**  
- `[5-3, 2-5, 33-2] = [2, -3, 31]`  

---

### 1️⃣2️⃣ Cumulative Sum (`np.cumsum(arr)`)  
- **Running total of candies:**  
- `[3, 3+5=8, 8+2=10, 10+33=43] = [3, 8, 10, 43]`  

---

### 1️⃣3️⃣ Linspace (`np.linspace(0, 10, 5)`)  
- Imagine spreading **candies evenly on a table** → `[0, 2.5, 5, 7.5, 10]`  

---

### 1️⃣4️⃣ Logarithm (`np.log(arr)`)  
- Transform candies **on a magic shrinking scale** → `[ln(3), ln(5), ln(2), ln(33)]`  
- It squashes big numbers to a smaller, more manageable range.

---

### 1️⃣5️⃣ Exponential (`np.exp(arr)`)  
- **Magic growing candies:** each candy multiplies by `e` that many times → `[e^3, e^5, e^2, e^33]`  

---

### 🎉 TL;DR Party Analogy
- `mean`, `median`, `percentile` → **average and relative position**  
- `std`, `var` → **how scattered the party is**  
- `sum`, `prod`, `cumsum`, `diff` → **total and changes**  
- `min`, `max`, `argmin`, `argmax`, `unique` → **special guests and candy uniqueness**  
- `log`, `exp` → **magical transformation of candies**  
- `linspace` → **evenly spread candies**  
- `corrcoef` → **party dancing in sync**  

Keep this analogy in mind, and you’ll **never forget what each NumPy function really does**! 🎈


In [1]:
import numpy as np

In [2]:
arr = np.array([3, 5, 2, 33])

In [3]:
np.mean(arr)

np.float64(10.75)

In [4]:
np.std(arr)

np.float64(12.891373084353738)

In [5]:
np.var(arr)


# Explanation:

# - Mean = (3+5+2+33)/4 = 43/4 = 10.75
# - Differences from mean = [-7.75, -5.75, -8.75, 22.25]
# - Squared differences = [60.06, 33.06, 76.56, 495.06]
# - Average of squared differences = 187.25

# So the variance is big because 33 is much larger than the others.

np.float64(166.1875)

In [6]:
np.min(arr) # Smallest element in the array → 2.

np.int64(2)

In [7]:
np.max(arr) # Largest element → 33.

np.int64(33)

In [8]:
np.sum(arr) # Adds everything: 3+5+2+33 = 43.

np.int64(43)

In [9]:
np.prod(arr) # Multiplies everything: 3 × 5 × 2 × 33 = 990.

np.int64(990)

In [10]:
np.median(arr)

# Sorted array = [2, 3, 5, 33].
# Median = average of middle two (3 and 5) = 4.0.

np.float64(4.0)

In [11]:
np.percentile(arr, 50)

# 50th percentile = median.
# Percentiles show “cut-off values”. For example, the 25th percentile is 25% of data below it.

np.float64(4.0)

In [12]:
np.argmin(arr) # 2 is the minimum, and its index in [3, 5, 2, 33] is 2.

np.int64(2)

In [13]:
np.argmax(arr) # 33 is the maximum, at index 3.

np.int64(3)

In [14]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])
np.corrcoef(arr1, arr2)  # Result will be close to 1, meaning perfect positive correlation.
# For a single arr you can just check correlation of arr with itself, which is always 1

array([[1., 1.],
       [1., 1.]])

In [15]:
my_arr = np.array([1,2,3,4,5,2,2,1])

In [16]:
np.unique(my_arr) # This returns only unique values

array([1, 2, 3, 4, 5])

In [17]:
np.diff(arr)

# 5-3 = 2
# 2-5 = -3
# 33-2 = 31
# So it shows the jumps between numbers.

array([ 2, -3, 31])

In [18]:
np.cumsum(arr)

# It keeps adding as you go:
# 3 → 3
# 3+5 → 8
# 8+2 → 10
# 10+33 → 43

array([ 3,  8, 10, 43])

In [19]:
np.linspace(3, 33, 4) # Divides the range from 3 to 33 into 4 equal steps.

array([ 3., 13., 23., 33.])

In [20]:
np.log(arr)

#Logarithms compress big numbers.
# Example: log(33) ≈ 3.5, while log(2) ≈ 0.69.

array([1.09861229, 1.60943791, 0.69314718, 3.49650756])

In [21]:
np.exp(arr)

# This is e^x for each element. It grows very fast.
# np.exp(33) is a huge number (~2.146e+14).

array([2.00855369e+01, 1.48413159e+02, 7.38905610e+00, 2.14643580e+14])